# Generated by Django 3.2.5 on 2021-07-23 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='the ip', max_length=200)),
                ('ip', models.TextField(max_length=60)),
                ('data_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('joke', models.TextField(max_length=200)),
                ('data_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
